### ISSUE TITLE
Комент

### ISSUE THREAD

**Issue by evgeniy-btw** [sqdsh/boticord-comments#16]
У меня есть два варианта что добавить:

1. Вот ты ему ручкой машешь, а он тебя трахнуть хочет! ©️ evgen1y

2. やめてください ©️ evgen1y

**Comment by MillerD3V** [comment]
1. А как тут что переключать ©️ MillerD3V
2. КУДА ТЫКОТЬ????? ©️ MillerD3V
3. смотри сюда 😣 ©️ MillerD3V
